(function(){
'use strict';
var collections=[{name:'Urban Toys (2008)',icon:'🎭',color:'#ffffff'},{name:'MegaTrip (2009)',icon:'🌌',color:'#ffffff'},{name:"Fut Gogo's (2010)",icon:'⚽',color:'#ffffff'},{name:'Turma da Mônica (2011)',icon:'🐰',color:'#ffffff'}];
var key='gogo-flex-v1', data={owned:[],history:[]};
try{var saved=JSON.parse(localStorage.getItem(key)||'null');if(saved && Array.isArray(saved.owned)&&Array.isArray(saved.history))data=saved}catch(e){}
var active=null,done=0,calMonth=new Date();calMonth.setDate(1);
function $(id){return document.getElementById(id)}function persist(){localStorage.setItem(key,JSON.stringify(data))}
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function localDate(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function fmt(d){return String(d).split('-').reverse().join('/')}
function icon(c){return (collections.find(function(x){return x.name===c})||collections[0]).icon}
function updateStats(){$('total-flex').textContent=data.history.reduce(function(a,x){return a+x.reps},0);$('total-days').textContent=new Set(data.history.map(function(x){return x.date})).size;$('total-gogos').textContent=data.owned.length}
function go(tab){document.querySelectorAll('[id^="tab-"]').forEach(function(el){el.classList.toggle('hidden',el.id!=='tab-'+tab)});document.querySelectorAll('[data-tab]').forEach(function(el){el.classList.toggle('active',el.dataset.tab===tab)});render()}
document.querySelectorAll('[data-tab]').forEach(function(b){b.addEventListener('click',function(){go(b.dataset.tab)})});
$('today').textContent=new Date().toLocaleDateString('pt-BR',{day:'2-digit',month:'short'});$('date').value=localDate(new Date());
function redrawTraining(){if(!active)return;var left=Math.max(0,active.number-done);$('reps').textContent=done;$('remaining').textContent=left===0?'Meta atingida!':'Faltam '+left+' flexões';$('training-bar').style.width=(Math.min(100,done/active.number*100))+'%';$('finish').disabled=done<active.number}
$('start').onclick=function(){var n=Number($('number').value),c=$('collection').value,d=$('date').value;if(!Number.isInteger(n)||n<1||n>999||!d){alert('Informe um número inteiro entre 1 e 999 e uma data.');return}var o=data.owned.find(function(x){return x.collection===c&&x.number===n});var name=$('gogo-name').value.trim()||(o&&o.name)||'';active={collection:c,number:n,name:name,date:d};done=0;$('training').classList.remove('hidden');$('challenge-number').innerHTML=n+' <em>flexões</em>';$('collection-badge').textContent=c;$('gogo-symbol').textContent=icon(c);$('gogo-title').textContent=name||'Gogo nº '+n;$('gogo-description').textContent='Gogo nº '+n+' • '+c+' • '+fmt(d);redrawTraining()};
$('plus').onclick=function(){if(active){done=Math.min(active.number,done+1);redrawTraining()}};$('plus5').onclick=function(){if(active){done=Math.min(active.number,done+5);redrawTraining()}};$('minus').onclick=function(){done=Math.max(0,done-1);redrawTraining()};
$('finish').onclick=function(){if(!active||done<active.number)return;data.history.unshift({id:Date.now(),collection:active.collection,number:active.number,name:active.name,date:active.date,reps:done});if(!data.owned.some(function(x){return x.collection===active.collection&&x.number===active.number}))data.owned.push({collection:active.collection,number:active.number,name:active.name});persist();$('portal-heading').textContent=(active.name||'Gogo nº '+active.number)+' entrou no Portal!';$('flying-gogo').textContent=icon(active.collection);$('flying-gogo').style.animation='none';void $('flying-gogo').offsetWidth;$('flying-gogo').style.animation='flight 2.5s ease-in forwards';$('portal-overlay').classList.remove('hidden');active=null;$('training').classList.add('hidden');$('number').value='';$('gogo-name').value='';updateStats()};
$('close-portal').onclick=function(){$('portal-overlay').classList.add('hidden');go('portal')};
$('save-owned').onclick=function(){var c=$('own-collection').value,n=Number($('own-number').value),name=$('own-name').value.trim();if(!Number.isInteger(n)||n<1||n>999){alert('Informe um número válido entre 1 e 999.');return}var old=data.owned.find(function(x){return x.collection===c&&x.number===n});if(old)old.name=name||old.name;else data.owned.push({collection:c,number:n,name:name});persist();$('own-number').value='';$('own-name').value='';render()};
function renderCollections(){$('collection-grid').innerHTML=collections.map(function(c){var arr=data.owned.filter(function(x){return x.collection===c.name});return '<button class="collection" data-choose="'+esc(c.name)+'"><span class="emoji">'+c.icon+'</span><strong>'+esc(c.name)+'</strong><span class="muted">'+arr.length+' cadastrados</span><div class="progress"><div class="fill" style="width:'+Math.min(100,arr.length)+'%;background:'+c.color+'"></div></div><span class="small">Abrir e registrar →</span></button>'}).join('');document.querySelectorAll('[data-choose]').forEach(function(b){b.onclick=function(){$('own-collection').value=b.dataset.choose;$('own-number').focus()}});$('owned-list').innerHTML=data.owned.length?data.owned.slice().sort(function(a,b){return a.collection.localeCompare(b.collection)||a.number-b.number}).map(function(x){return '<div class="record"><div><b>'+icon(x.collection)+' '+esc(x.name||'Gogo nº '+x.number)+'</b><small>#'+x.number+' • '+esc(x.collection)+'</small></div><button class="ghost" data-remove="'+esc(x.collection)+'|'+x.number+'">Remover</button></div>'}).join(''):'<p class="hint">Nenhum bonequinho cadastrado ainda.</p>';document.querySelectorAll('[data-remove]').forEach(function(b){b.onclick=function(){var p=b.dataset.remove.split('|');data.owned=data.owned.filter(function(x){return !(x.collection===p[0]&&x.number===Number(p[1]))});persist();render()}})}
function renderHistory(){$('history').innerHTML=data.history.length?data.history.map(function(x){return '<div class="record"><div><b>'+icon(x.collection)+' '+esc(x.name||'Gogo nº '+x.number)+'</b><small>'+fmt(x.date)+' • '+esc(x.collection)+'</small></div><strong>'+x.reps+' 💪</strong></div>'}).join(''):'<p class="hint">Nenhum desafio concluído. Seu primeiro Gogo está esperando!</p>';$('victory-list').innerHTML=data.history.length?data.history.map(function(x){return '<div class="record"><div><b>✨ '+esc(x.name||'Gogo nº '+x.number)+'</b><small>'+fmt(x.date)+' • '+esc(x.collection)+'</small></div><span class="tag">'+x.reps+' flexões</span></div>'}).join(''):'<p class="hint">O portal ainda aguarda seu primeiro visitante.</p>'}
function renderCalendar(){var year=calMonth.getFullYear(),month=calMonth.getMonth();$('month-label').textContent=calMonth.toLocaleDateString('pt-BR',{month:'long',year:'numeric'});var first=new Date(year,month,1),length=new Date(year,month+1,0).getDate(),start=first.getDay();var s=['D','S','T','Q','Q','S','S'].map(function(x){return '<div class="week">'+x+'</div>'}).join('');for(var i=0;i<start;i++)s+='<div></div>';for(var d=1;d<=length;d++){var date=localDate(new Date(year,month,d)),records=data.history.filter(function(x){return x.date===date});s+='<div class="day '+(records.length?'done':'')+'" title="'+records.length+' desafio(s)">'+d+(records.length?'<div>⭐ '+records.length+'</div>':'')+'</div>'}$('calendar').innerHTML=s}
$('prev-month').onclick=function(){calMonth.setMonth(calMonth.getMonth()-1);renderCalendar()};$('next-month').onclick=function(){calMonth.setMonth(calMonth.getMonth()+1);renderCalendar()};
$('export').onclick=function(){var blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='gogo-flex-backup.json';a.click();setTimeout(function(){URL.revokeObjectURL(url)},1000)};
function render(){updateStats();renderCollections();renderHistory();renderCalendar()}render();
})();
